export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Home } from './Home'
export { default as Pets } from './Pets'
export { default as CDRvaci } from './CDRvaci'